// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://orbbxvibqgvcdzruqxkm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9yYmJ4dmlicWd2Y2R6cnVxeGttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3MzUxOTcsImV4cCI6MjA1NjMxMTE5N30.Nf0FFO9WbgtVMXD5H42ZUCSVciWRwhljVsANbJL6thk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);